"""
emailer.py — Email delivery module for ArthaMind
Sends AI-generated PDF reports via Gmail SMTP using App Password.
"""

import smtplib
import os
from html import escape
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
from dotenv import load_dotenv

load_dotenv()


def _parse_recipients(raw_recipients: str) -> list[str]:
    return [email.strip() for email in raw_recipients.split(",") if email.strip()]


def send_report_email(to_email: str, company_name: str, fy_label: str,
                       pdf_bytes: bytes, sender_note: str = "") -> tuple[bool, str]:
    """
    Send the generated PDF report to `to_email`.
    Returns (success: bool, message: str)
    
    Required .env variables:
        EMAIL_SENDER       — your Gmail address
        EMAIL_APP_PASSWORD — Gmail App Password (16 chars, no spaces)
                             Generate at: myaccount.google.com/apppasswords
    """
    sender_email = os.getenv("EMAIL_SENDER", "")
    app_password  = os.getenv("EMAIL_APP_PASSWORD", "")
    recipients = _parse_recipients(to_email)

    if not sender_email or not app_password:
        return False, (
            "Email credentials not configured. "
            "Add EMAIL_SENDER and EMAIL_APP_PASSWORD to your .env file. "
            "Get an App Password at: myaccount.google.com/apppasswords"
        )
    if not recipients:
        return False, "Enter at least one recipient email address."

    subject = f"ArthaMind | {company_name} — {fy_label} Projection Report"
    safe_company_name = escape(company_name)
    safe_fy_label = escape(fy_label)
    safe_sender_note = escape(sender_note).replace("\n", "<br>")

    html_body = f"""
    <html><body style="font-family: Inter, Arial, sans-serif; background:#f8fafc; padding:30px;">
      <div style="max-width:600px;margin:0 auto;background:white;border-radius:12px;
                  box-shadow:0 4px 20px rgba(0,0,0,0.08);overflow:hidden;">
        <div style="background:linear-gradient(135deg,#0a1628,#0f2744);padding:32px 36px;">
          <div style="font-size:24px;font-weight:800;color:#10b981;">📊 ArthaMind</div>
          <div style="font-size:13px;color:#94a3b8;margin-top:4px;">AI Financial Intelligence Platform</div>
        </div>
        <div style="padding:32px 36px;">
          <h2 style="color:#0a1628;margin:0 0 12px 0;">Your Report is Ready</h2>
          <p style="color:#475569;line-height:1.6;">
            Please find attached the <strong>{safe_fy_label} Projection Report</strong> 
            for <strong>{safe_company_name}</strong>, generated by ArthaMind AI.
          </p>
          {f'<p style="color:#64748b;font-style:italic;font-size:13px;border-left:3px solid #10b981;padding-left:12px;">{safe_sender_note}</p>' if sender_note else ''}
          <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:16px;margin-top:20px;">
            <p style="color:#166534;margin:0;font-size:13px;">
              ⚠️ <strong>Disclaimer:</strong> This report contains AI-generated forward-looking projections 
              based on historical data. It does not constitute financial advice. Actual results may differ 
              materially from projections.
            </p>
          </div>
        </div>
        <div style="background:#f8fafc;padding:20px 36px;border-top:1px solid #e2e8f0;">
          <p style="color:#94a3b8;font-size:12px;margin:0;">
            Sent via ArthaMind AI Platform &nbsp;|&nbsp; 
            <a href="https://arthamind.ai" style="color:#10b981;">arthamind.ai</a>
          </p>
        </div>
      </div>
    </body></html>
    """

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = f"ArthaMind AI <{sender_email}>"
        msg["To"]      = ", ".join(recipients)

        msg.attach(MIMEText(html_body, "html"))

        # Attach PDF
        attachment = MIMEBase("application", "pdf")
        attachment.set_payload(pdf_bytes)
        encoders.encode_base64(attachment)
        filename = f"{company_name.replace(' ', '_')}_{fy_label}_Projection.pdf"
        attachment.add_header("Content-Disposition", f'attachment; filename="{filename}"')
        msg.attach(attachment)

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender_email, app_password)
            server.sendmail(sender_email, recipients, msg.as_string())

        if len(recipients) == 1:
            return True, f"Report successfully sent to {recipients[0]} ✅"
        return True, f"Report successfully sent to {len(recipients)} recipients ✅"

    except smtplib.SMTPAuthenticationError:
        return False, (
            "Gmail authentication failed. Make sure:\n"
            "1. EMAIL_SENDER is your full Gmail address\n"
            "2. EMAIL_APP_PASSWORD is a valid 16-char App Password\n"
            "   (not your regular Gmail password)\n"
            "Generate one at: myaccount.google.com/apppasswords"
        )
    except Exception as e:
        return False, f"Email failed: {str(e)}"
